---
- hosts: Prod
  gather_facts: false
  become: True
  collections:
    - community.kubernetes
  tasks:
  
    - name: Create a k8s namespace
      k8s:
        state: present
        definition:
        src: namespace.yaml
        
     
    - name: Create a Service object
      k8s:
        state: present
        definition:
        src: Service.yaml
     
    - name: Create a Deployment object
      k8s:
        state: present
        definition:
        src: deployment.yaml
