apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deploy
  labels:
    app: simple-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - name: simple-app-container
        image: rajputmarch2020/java_app:{{DOCKER_TAG}}
        ports:
        - containerPort: 8080
      
