---
- hosts: Prod
  gather_facts: false
  become: True
  collections:
    - community.kubernetes
    
  tasks:
    #- name: Create a k8s namespace
     # k8s:
      #  name: Prod
       # api_version: v1
        #kind: Namespace
        #state: present
          
    - name: Create a Service object
      community.kubernetes.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: simple-app-service
            namespace: default
            labels:
              app: simple-app
          spec:
            selector:
              app: simple-app
            type: NodePort
            ports:
            - nodePort: 31000
              port: 8080
              targetPort: 8080
      
          
     
    - name: Create a Deployment object
      k8s:
        state: present
        definition:
        src: deployment.yaml
