apiVersion: v1
kind: Service
metadata:
  name: simple-app-service
  namespace: Prod
  labels:
    app: simple-app
spec:
  selector:
    app: simple-app
  type: NodePort
    ports:
    - nodePort: 31000
      port: 8080
      targetPort: 8080
      
